services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_NODE_ENV: ${REACT_APP_NODE_ENV}
        REACT_APP_API: ${REACT_APP_API}
        REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
        REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID}
        REACT_APP_FIREBASE_PROJECT_BUCKET: ${REACT_APP_FIREBASE_PROJECT_BUCKET}
        REACT_APP_FIREBASE_MESSAGE_ID: ${REACT_APP_FIREBASE_MESSAGE_ID}
        REACT_APP_FIREBASE_APP_ID: ${REACT_APP_FIREBASE_APP_ID}
        REACT_APP_MEASURE_ID: ${REACT_APP_MEASURE_ID}
    container_name: urban-chowk-client
    volumes:
      - ./:/var/www/app
      - /app/node_modules/
      - /app/node_modules/node-sass/vendor
    ports:
      - 3000:3000
    environment:
      env_file: .env
      PORT: 3000
    command: sh -c 'npm i && npm start'