services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        API: ${API}
        FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
        FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        FIREBASE_PROJECT_BUCKET: ${FIREBASE_PROJECT_BUCKET}
        FIREBASE_MESSAGE_ID: ${FIREBASE_MESSAGE_ID}
        FIREBASE_APP_ID: ${FIREBASE_APP_ID}
        MEASURE_ID: ${MEASURE_ID}
    container_name: urban-chowk-client
    volumes:
      - ./:/var/www/app
      - /app/node_modules/
      - /app/node_modules/node-sass/vendor
    ports:
      - 3000:3000
    environment:
      env_file: .env
      PORT: 3000
    command: sh -c 'npm i && npm start'