const LOGIN = {
  LOGIN_ACTION_LOADING: "LOGIN_ACTION_LOADING",
  LOGIN_ACTION_SUCCESS: "LOGIN_ACTION_SUCCESS",
  LOGIN_ACTION_FAILURE: "LOGIN_ACTION_FAILURE",
};

const SIGNUP = {
  SIGNUP_ACTION_LOADING: "SIGNUP_ACTION_LOADING",
  SIGNUP_ACTION_SUCCESS: "SIGNUP_ACTION_SUCCESS",
  SIGNUP_ACTION_FAILURE: "SIGNUP_ACTION_FAILURE",
};

const USER = {
  FORGET_USER_PASSWORD_ACTION_LOADING: "FORGET_USER_PASSWORD_ACTION_LOADING",
  FORGET_USER_PASSWORD_ACTION_SUCCESS: "FORGET_USER_PASSWORD_ACTION_SUCCESS",
  FORGET_USER_PASSWORD_ACTION_FAILURE: "FORGET_USER_PASSWORD_ACTION_FAILURE",
};

const TESTIMONIAL = {
  GET_TESTIMONIAL_ACTION_LOADING: "GET_TESTIMONIAL_ACTION_LOADING",
  GET_TESTIMONIAL_ACTION_SUCCESS: "GET_TESTIMONIAL_ACTION_SUCCESS",
  GET_TESTIMONIAL_ACTION_FAILURE: "GET_TESTIMONIAL_ACTION_FAILURE",

  DELETE_TESTIMONIAL_ACTION_LOADING: "DELETE_TESTIMONIAL_ACTION_LOADING",
  DELETE_TESTIMONIAL_ACTION_SUCCESS: "DELETE_TESTIMONIAL_ACTION_SUCCESS",
  DELETE_TESTIMONIAL_ACTION_FAILURE: "DELETE_TESTIMONIAL_ACTION_FAILURE",

  ADD_TESTIMONIAL_ACTION_LOADING: "ADD_TESTIMONIAL_ACTION_LOADING",
  ADD_TESTIMONIAL_ACTION_SUCCESS: "ADD_TESTIMONIAL_ACTION_SUCCESS",
  ADD_TESTIMONIAL_ACTION_FAILURE: "ADD_TESTIMONIAL_ACTION_FAILURE",
};

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  LOGIN,
  SIGNUP,
  USER,
  TESTIMONIAL,
};
